---
argument_specs:
  main:
    short_description: 'Install and configure baseline utilities and settings on proxmox servers'
    description: >
      Installs packages, sets hostname, configures clustering for proxmox.
    author: Jeremy McNab
    options:
      bl_proxmox_enterprise_license:
        type: 'bool'
        default: false
        description: 'Flag to set no-subscription repo for packages.'
      bl_proxmox_apply_updates:
        type: 'bool'
        default: false
        description: 'Flag to determine if packages should be updated.'
      bl_proxmox_packages_default:
        type: 'list'
        default: ['openvswitch-switch', 'python3-pexpect', 'snmpd', 'jq']
        description: 'List of default packages that should be installed on every server.'
      bl_proxmox_packages_add:
        type: 'list'
        default: []
        description: 'List of additional packages that should be installed on every server.'
      bl_proxmox_packages_remove:
        type: 'list'
        default: []
        description: 'List of packages that should be removed from every server.'

      usi_server_mounts:
        type: 'list'
        elements: 'dict'
        default: []
        description: 'A list of dictionaries to configure mounts using the ansible.posix.mount module.'
        options:
          backup:
            type: 'bool'
            default: false
            description: 'Create a backup of the fstab file.'
          boot:
            type: 'bool'
            default: true
            description: 'Whether the mount is a boot mount.'
          dump:
            type: 'str'
            default: '0'
            description: 'Value to pass to the dump field in fstab.'
          fstab:
            type: 'path'
            default: '/etc/fstab'
            description: 'Path to the fstab file. Do not change unless you know what you are doing.'
          fstype:
            type: 'str'
            description: 'Filesystem type. Required if state is mounted, present, or ephemeral.'
          opts:
            type: 'str'
            description: 'Mount options detailed in fstab(4).'
          opts_no_log:
            type: 'bool'
            default: false
            description: 'Do not log opts.'
          passno:
            type: 'str'
            default: '0'
            description: 'Value to pass to the passno field in fstab.'
          path:
            type: 'path'
            required: true
            description: 'Mount point.'
          src:
            type: 'str'
            description: 'Device or remote filesystem to be mounted.'
          state:
            type: 'str'
            default: 'mounted'
            choices:
              - 'absent'
              - 'absent_from_fstab'
              - 'mounted'
              - 'present'
              - 'unmounted'
              - 'remounted'
              - 'ephemeral'
            description: 'Whether the mount should exist or not, taking action if the state is different.'
      usi_server_snmpd_loopback:
        type: 'list'
        default: ['127.0.0.1', '[::/0]']
        description: 'Binding loopback addresses for snmpd daemon.'
      usi_server_snmpd_addresses:
        type: 'list'
        default: ["{{ ansible_host }}"]
        description: 'Binding addresses for snmpd daemon.'
      usi_server_snmpd_allowed:
        type: 'list'
        default: ['rocommunity usiread 10.1.0.0/24']
        description: 'List of rocommunities for the SNMPD configuration template.'
      usi_server_snmpd_config:
        type: 'list'
        default: []
        description: 'List of raw SNMP configurations as they would appear in snmpd.conf - one list item per line.'
      usi_server_groups:
        type: 'list'
        elements: 'dict'
        default: []
        description: >
          List of dictionaries to add additional groups according to the ansible.builtin.groups module.
        options:
          name:
            type: 'str'
            description: 'Name of the group to create or remove.'
          state:
            type: 'str'
            default: 'present'
            choices:
              - 'absent'
              - 'present'
            description: 'Whether the group should exist or not, taking action if the state is different from what is stated.'
          system:
            type: 'bool'
            default: false
            description: 'Indicates that the created group is a system group (uses GID < 1000)'
      usi_server_users:
        type: 'list'
        elements: 'dict'
        default: []
        description: >
          List of dictionaries for additional users according to the ansible.builtin.users module.
        options:
          name:
            type: 'str'
            description: 'Name of the user to create, remove or modify.'
          groups:
            type: 'list'
            elements: 'str'
            default: []
            description: 'A list of supplementary groups which the user is a member of.'
          append:
            type: 'bool'
            description: 'Append group membership instead of replacing with defined groups list.'
          state:
            type: 'str'
            default: 'present'
            choices:
              - 'absent'
              - 'present'
            description: 'Whether the account should exist or not, taking action if the state is different from what is stated.'
          shell:
            type: 'path'
            default: '/bin/bash'
            description: 'Set the user shell'
          password:
            type: 'str'
            default: '*'
            description: 'If provided, set the user password to the provided encrypted hash'
          create_home:
            type: 'bool'
            default: true
            description: 'Create the user home directory if it does not exist'
          authorized_keys:
            type: 'list'
            elements: 'str'
            default: []
            description: 'A list of authorized keys to be added to the user profile.'
          home:
            type: 'path'
            description: 'Set the user home directory. Defaults to /home/<username>'
      usi_server_use_default_motd:
        type: 'bool'
        default: true
        description: 'Include the default message-of-the-day template.'
      usi_server_custom_motd:
        type: 'list'
        elements: 'str'
        default: []
        description: 'A list of strings to add as lines in the MOTD.'
      usi_server_authorized_keys:
        type: 'list'
        elements: 'dict'
        default: []
        description: 'A list of dicts for adding authorized keys to named users.'
      usi_server_add_packages:
        type: 'list'
        elements: 'str'
        default: []
        description: 'A list of strings for adding additional packages.'
      usi_server_remove_packages:
        type: 'list'
        elements: 'str'
        default: []
        description: 'A list of strings for removing unwanted packages.'
      usi_server_set_mirror:
        type: 'bool'
        default: false
        description: 'Set the APT mirror to the USI mirror.'
      usi_server_services:
        type: 'list'
        elements: 'dict'
        default: []
        description: 'A list of dicts for managing systemd services.'
        options:
          daemon_reexec:
            type: 'bool'
            default: false
            description: 'Run daemon_reexec before other operations.'
          daemon_reload:
            type: 'bool'
            default: false
            description: 'Run daemon_reload before other operations.'
          enabled:
            type: 'bool'
            description: 'Whether the service should be enabled or not.'
          force:
            type: 'bool'
            description: 'Override existing symlinks.'
          masked:
            type: 'bool'
            description: 'Whether the service should be masked or not.'
          name:
            type: 'str'
            required: true
            description: 'Name of the service to manage.'
          no_block:
            type: 'bool'
            default: false
            description: 'Do not synchronsously wait for the operation to complete.'
          state:
            type: 'str'
            description: 'State of the service.'
      usi_server_debug:
        type: 'bool'
        default: false
        description: 'Enable role debug mode for additional output.'
      usi_server_ubuntu_pro_enable:
        type: 'bool'
        default: true
        description: 'Enable Ubuntu Pro services.'
      usi_ubuntu_pro_services:
        type: 'list'
        elements: 'str'
        default:
          - 'esm-apps'
          - 'esm-infra'
          - 'livepatch'
        description: 'List of Pro services to enable.'
      usi_ubuntu_pro_token:
        type: 'str'
        default: 'C12JZ9EUvJMuj9FtbFojZL3JzAJiJp'
        description: 'Ubuntu Pro services registration token.'
      usi_server_edr_install:
        type: 'bool'
        default: false
        description: 'Enable install of Cisco AMP EDR.'
      usi_server_edr_url:
        type: 'str'
        default: "https://content.usinternet.com/downloads/cisco/amp_Linux_Audit_No_Proxy_ubuntu-20-04-amd64.deb"
        description: 'Download url for Cisco AMP EDR.'
      usi_server_edr_user:
        type: 'str'
        default: "ciscoamp"
        description: 'Username required to download the package.'
      usi_server_edr_pass:
        type: 'str'
        default: "YmQ5YWIzNWEzOTczOGEwNjg4YWE2NmNh"
        description: 'Password required to download the package.'
      usi_server_edr_debug:
        type: 'bool'
        default: false
        description: 'Enable debug logging for EDR package download.'
      usi_server_vas_install:
        type: 'bool'
        default: false
        description: 'Enable install of Qualys VAS client.'
      usi_server_vas_url:
        type: 'str'
        default: "https://content.usinternet.com/downloads/qualys/client/QualysCloudAgent.deb"
        description: 'Download url for Qualys VAS client.'
      usi_server_vas_user:
        type: 'str'
        default: "qualysvas"
        description: 'Username required to download the package.'
      usi_server_vas_pass:
        type: 'str'
        default: "YmQ5YWIzNWEzOTczOGEwNjg4YWE2NmNh"
        description: 'Password required to download the package.'
      usi_server_vas_debug:
        type: 'bool'
        default: false
        description: 'Enable debug logging for VAS package download.'
      usi_server_vas_activation_id:
        type: 'str'
        default: '8b8357b7-3802-46a1-b0f2-b4bcc502b7de'
        description: 'Qualys VAS activation ID.'
      usi_server_vas_customer_id:
        type: 'str'
        default: '11901e41-f793-6289-8027-abab2d20aa2e'
        description: 'Qualys VAS customer ID.'
      usi_server_vas_server_uri:
        type: 'str'
        default: "https://qagpublic.qg3.apps.qualys.com/CloudAgent/"
        description: 'Qualys VAS cloud agent activation URI.'
