# SUBSCRIPTION OR NO
bl_proxmox_enterprise_license: false

# APT/UPDATES
bl_proxmox_apply_updates: false
bl_proxmox_keyring: /usr/share/keyrings/proxmox-archive-keyring.gpg

# PACKAGES
bl_proxmox_packages_default:
  - openvswitch-switch
  - python3-pexpect
  - jq

bl_proxmox_packages_add: []
bl_proxmox_packages_remove: []
bl_proxmox_packages_update: false
# bl_proxmox_packages_autostart: false


# CEPH INSTALL
bl_proxmox_ceph_enabled: false
bl_proxmox_ceph_repository: 'no-subscription'
bl_proxmox_ceph_version: 'squid'

# BUILD OUR HOST ID BASED ON LAST OCTET TO USE FOR PVE ADDRESS OR OTHER USES
bl_proxmox_host_octet: "{{ ansible_host | split('.') | last }}"
bl_proxmox_interfaces: []
# Example:
# bl_proxmox_interfaces:
#  #management
#  - name: eno5
#    address: "{{ ansible_host }}"
#    netmask: 255.255.255.0
#    gateway: 10.255.255.1
#    family: inet
#    method: static
#    comment: "out of band management network"
#  - name: eno6
#  - name: ens7f0
#  - name: ens7f1
#  - name: vmk0
#    method: static
#    address: "172.16.65.{{ bl_proxmox_host_octet }}/24"
#    ovs_type: OVSIntPort
#    ovs_bridge: vmbr0
#    ovs_options: tag=1065
#    comment: "pve cluster network"

bl_proxmox_pve_network: "172.16.0.0"
bl_proxmox_pve_network_mask: "24"
bl_proxmox_pve_network_address: "{{ bl_proxmox_pve_network.split('.')[:3] | join('.') }}.{{ bl_proxmox_host_octet }}"

# HOSTS and DOMAINS
bl_proxmox_tld: 'bridgelinetech.com'
bl_proxmox_hosts_domains:
  - "{{ bl_proxmox_tld }}"

bl_proxmox_hosts_groups: ["{{ group_names[0] }}"]
bl_proxmox_hosts_list: []

# DEFAULT OUR hostvar to bl_proxmox_pve_network_address or ansible_host
bl_proxmox_ipv4_var: "{{ bl_proxmox_pve_network_address | default('ansible_host') }}"
bl_proxmox_ipv6_var: "{{ undef() }}"


# CLUSTER configuration
bl_proxmox_cluster_enabled: false
bl_proxmox_cluster_join: false
bl_proxmox_cluster_name: "pve-cluster"
bl_proxmox_cluster_fingerprint: ""
bl_proxmox_cluster_master: ""
bl_proxmox_cluster_nodes: []

# SPECIAL ROUTING - Todo
bl_proxmox_custom_routes: []
# Example:
# bl_proxmox_custom_routes:
#   - destination: "10.0.0.0/24"
#     gateway: "192.168.1.254"
#     interface: "vmbr1"

bl_proxmox_force_reload: false

bl_proxmox_snmpd: {}
bl_proxmox_snmpd_defaults:
  enabled: false
  sys_location: "Rack00"
  sys_contact: "Bridgeline Tech <admin@bridgelinetech.com>"
  sys_services: "72"
  loopback: 127.0.0.1
  listen_addresses:
    - "{{ ansible_host }}"
  rules:
    - address: 127.0.0.1
      community: public
      access: rocommunity
  custom: []

bl_proxmox_snmpd_config: "{{ bl_proxmox_snmpd_defaults | ansible.builtin.combine(bl_proxmox_snmpd, recursive=true) }}"

bl_proxmox_timezone: America/Chicago
bl_proxmox_timeserver: pool.ntp.org